### ISSUE TITLE
ACPI decoded tables useless

### ISSUE THREAD

**Issue by nyov** [linuxhw/ACPI#1]
I like the idea behind this project. But sadly the ACPI data dumps here are somewhat useless.

The information that would actually be useful and re-useable is the unmodified output of 
`acpidump -o acpidump.txt`, because that contains everything needed to extract the binary tables (what `acpidump -b` fetches directly) _and_ to recompile the tables:
`acpixtract -l acpidump.txt` to list them, `acpixtract -a acpidump.txt` to extract them.

This is not possibly with the current decompiled data dump.
Because the decompiled dumps didn't use external symbol resolution (iasl `-da` or `-e` mode), important information is lost.
Also the ASL source language changes from time to time (see ASL2.0), so using that as a source for recompiling will break whenever ACPICA asl syntax moves on.

So before you collect more unusable data, I hope you'll switch to storing (at least) the binary dumps, which would also save a ton of space by comparison. All the other info can be extracted from those.

**Comment by linuxhw** [comment]
Fixed by commit https://github.com/linuxhw/hw-probe/commit/a45729b4c743feae2e6be2266f173fa469a66b0b.

Thanks.

**Comment by nyov** [comment]
And thank you!

**Comment by linuxhw** [comment]
@nyov,

Binary dumps will be saved to `*.bin` files near decoded ones:

https://github.com/linuxhw/ACPI/blob/master/Desktop/Supermicro/X8/X8SIL/40AECBFF4573.bin
https://github.com/linuxhw/ACPI/blob/master/Desktop/Supermicro/X8/X8SIL/40AECBFF4573

Please check if this fits your needs.

Thank you.

**Comment by nyov** [comment]
Yes I saw this. It works for me, and I think with this information, it is future-proof now.
